source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in tensai.gemspec
gemspec

group :development, :test do
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 0.74'
  gem 'rubocop-rspec', '~> 1.35'
  gem 'guard', '~> 2.15'
  gem 'guard-rspec', '~> 4.7'
  gem 'pry-byebug', '~> 3.7'
  gem 'factory_bot', '~> 5.0'
end
